spring:
  datasource:
    url: jdbc:mysql://localhost:3306/uptask?useSSL=false&ServerTimezone=UTC
    username: root
    password: Chiquilin43
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect